export type {
  CoChangeEvent,
  CoChangePairCount,
  CompareMeta,
  CompareResult,
  ComplexityResult,
  CouplingPair,
  DiagnosticSeverity,
  StaticDependencyDirection,
  FileChangeStats,
  HotspotCompareSection,
  HotspotScore,
  RankChange,
  ScanMeta,
  ScanOptions,
  ScanProgress,
  ScanProgressPhase,
  ScanResult,
  ScanStageTimings,
  ScanWarning,
} from "./domain.js";
