/**
 * Barrel re-export for living SoT doc helpers.
 * Ownership matrix SoT: `.specs/codebase/DOC-OWNERSHIP.md`.
 */

export {
  AGENT_ROLES_DIR_REL_PATH,
  AGENTS_LINE_WARN,
  AGENTS_REL_PATH,
  ARCHITECTURE_REL_PATH,
  CONCERNS_REL_PATH,
  CONTRIBUTING_LINE_WARN,
  CONTRIBUTING_REL_PATH,
  CONVENTIONS_REL_PATH,
  DOC_OWNERSHIP_REL_PATH,
  DOCS_CLI_REFERENCE_REL_PATH,
  DOCS_METHODOLOGY_REL_PATH,
  DOCS_RECIPES_REL_PATH,
  DOCS_WARNING_CODES_REL_PATH,
  INTEGRATIONS_REL_PATH,
  isAgentRoleDocPath,
  isAgentsDocPath,
  isArchitectureDocPath,
  isConcernsDocPath,
  isConventionsDocPath,
  isContributingDocPath,
  isDocOwnershipDocPath,
  isDocsUserDocPath,
  isIntegrationsDocPath,
  isProjectDocPath,
  isReadmeDocPath,
  isRoadmapDocPath,
  isSkillDocPath,
  isStackDocPath,
  isStateDocPath,
  isStructureDocPath,
  isTestingDocPath,
  LINE_WARN,
  PROJECT_REL_PATH,
  README_LINE_WARN,
  README_REL_PATH,
  ROADMAP_LINE_WARN,
  ROADMAP_REL_PATH,
  SKILLS_DIR_REL_PATH,
  STACK_REL_PATH,
  STATE_LINE_WARN,
  STATE_REL_PATH,
  STRUCTURE_REL_PATH,
  TESTING_REL_PATH,
} from "./living-sot-paths.mjs";

export {
  lintAgentRolesDoc,
  lintAgentsDoc,
  lintArchitectureDoc,
  lintBannedTags,
  lintConcernsDoc,
  lintConventionsDoc,
  lintContributingDoc,
  lintDocOwnershipDoc,
  lintDocsUserDoc,
  lintIntegrationsDoc,
  lintProjectDoc,
  lintReadmeDoc,
  lintRoadmapDoc,
  lintSkillsDoc,
  lintStackDoc,
  lintStateDoc,
  lintStructureDoc,
  lintTestingDoc,
} from "./living-sot-lints.mjs";

export {
  AGENT_ROLES_SOT_CONTEXT,
  AGENTS_SOT_CONTEXT,
  ARCHITECTURE_SOT_CONTEXT,
  CONCERNS_SOT_CONTEXT,
  CONTRIBUTING_SOT_CONTEXT,
  CONVENTIONS_SOT_CONTEXT,
  DOC_OWNERSHIP_SOT_CONTEXT,
  DOCS_SOT_CONTEXT,
  INTEGRATIONS_SOT_CONTEXT,
  LIVING_SOT_ENTRIES,
  PROJECT_SOT_CONTEXT,
  README_SOT_CONTEXT,
  ROADMAP_SOT_CONTEXT,
  SKILLS_SOT_CONTEXT,
  STACK_SOT_CONTEXT,
  STATE_SOT_CONTEXT,
  STRUCTURE_SOT_CONTEXT,
  TESTING_SOT_CONTEXT,
} from "./living-sot-registry.mjs";
